name: Node.js CI with Caching

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'  # Automatically caches 'node_modules'

      - name: Install Dependencies
        run: npm ci  # Uses cached dependencies if available

      - name: Run Application
        run: npm start
